package com.tropig.backend.contents.enums

enum class PublishingType(val displayName: String) {
    CHARACTER_SHEET("캐릭터 시트"),
    IMAGE("이미지"),
    COCOFORIA("코코포리아"),
    ROLL20("롤20"),
    HOUSE_RULE("하우스룰"),
    SUB_RULE("보조룰"),
    SYSTEM_SUMMARY("시스템 요약"),
    BATTLE_RULE("전투 규칙"),
    PDF("PDF"),
    BGM("BGM"),
    DOCX("글"),
    TOKEN("토큰"),
    NPC("NPC"),
    MAP("지도"),
    ITEM("아이템"),
    FVTT("FVTT"),
    BOT("봇"),
    TEMPLATE("템플릿"),
    ETC("기타"),
    EXTERNAL_LINK("외부 링크"),
    EXTERNAL_FILE(""),
    SCENARIO(""),
}
