# 계좌번호 검증 API 설정

# 토스페이먼츠 API 설정
toss:
  api:
    key: ${TOSS_API_KEY:your-toss-api-key}
    secret: ${TOSS_SECRET_KEY:your-toss-secret-key}
    base-url: https://api.tosspayments.com/v1
    timeout: 5000
    retry-count: 3
    account-validation:
      enabled: true
      timeout: 5000
      retry-count: 3

# 계좌번호 검증 설정
account-validation:
  # 검증 방법 우선순위 (비용이 낮은 순서)
  methods:
    - FORMAT    # 무료
    - CACHE     # 무료
    - TOSS      # 유료 (토스페이먼츠)
    - TRANSFER  # 유료 (송금 수수료)
  
  # 캐시 설정
  cache:
    enabled: true
    ttl: 86400  # 24시간 (초)
    max-size: 10000
  
  # 형식 검증 설정
  format-validation:
    enabled: true
    strict-mode: false  # 엄격한 검증 모드
  
  # API 호출 제한
  api-limits:
    daily-limit: 1000
    monthly-limit: 30000
    rate-limit: 100  # 분당 요청 수

# Spring 설정
spring:
  cache:
    type: simple