spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

jwt:
  secret: "your256bitSecretKeyPleaseChangeItThisIsTestTest"
  expiration: 3600000
  refresh-expiration: 86400000
