spring:
  profiles:
    active: ${PROFILES_ACTIVE:local}

  datasource:
    url: jdbc:postgresql://postgresql-dev-service.tropig-dev.svc.cluster.local:5432/tropig_dev
    username: ${DB_USERNAME:tropig_user}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      platform: postgresql
      mode: always
      schema-locations: classpath:schema-postgresql.sql

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=100,expireAfterWrite=10m

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.tropig.backend: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1시간 (ms)
  refresh-expiration: 86400000 # 24H