package com.tropig.backend.common.enums

enum class MessageCode {
    NOT_FOUND_MEMBER,
    NOT_FOUND_CONTENT,
    NOT_FOUND_PURCHASE_INFO,
    NOT_FOUND_PAYMENT_INFO,
    NOT_FOUND_CONTENT_INFO,
    INCORRECT_ROLE,
    NOT_OWN_CONTENT,
    NOT_OWN_PAYMENT_INFO,
    CANNOT_REJOIN_MEMBER,
    ALREADY_EXISTS,
    ALREADY_EXISTS_MEMBER,
    ALREADY_PURCHASED,
    WITHDRAW_MEMBER,
    ADULT_CONTENT,
    OWN_CONTENT,
}