package com.tropig.backend.common.enums

enum class MessageCode {
    NOT_FOUND_MEMBER,
    WITHDRAWAL_MEMBER,
    ALREADY_AUTHENTICATED_ADULT,
    ALREADY_AUTHENTICATED_BANK_ACCOUNT,
    UNAUTHENTICATED_ADULT,
    NOT_ADULT_USER,
    UNEQUAL_MEMBER_NAME,
}