package com.tropig.backend.common.enums

enum class MessageCode {
    NOT_FOUND_MEMBER,
    NOT_FOUND_CONTENT,
    NOT_FOUND_PURCHASE_INFO,
    NOT_FOUND_PAYMENT_INFO,
    NOT_FOUND_CONTENT_INFO,
    INCORRECT_ROLE,
    NOT_OWN_CONTENT,
    NOT_OWN_PAYMENT_INFO,
    CANNOT_REJOIN_MEMBER,
    ALREADY_EXISTS,
    ALREADY_EXISTS_MEMBER,
    ALREADY_PURCHASED,
    WITHDRAW_MEMBER,
    ADULT_CONTENT,
    OWN_CONTENT,
    PURCHASE_REQUIRED,
    INVALID_PARAMS,

    // Identity Verification
    ALREADY_VERIFIED,
    INVALID_PHONE_NUMBER,
    INVALID_ID_NUMBER,
    INVALID_CARRIER,
    VERIFICATION_NOT_FOUND,
    VERIFICATION_NOT_INITIATED,
    OTP_EXPIRED,
    INVALID_OTP,
    OTP_ATTEMPTS_EXCEEDED,
    RESEND_LIMIT_EXCEEDED,

    // Duplicate Prevention
    CI_ALREADY_EXISTS,
    DI_ALREADY_EXISTS,

    // External Service
    EXTERNAL_SERVICE_ERROR,
    PORTONE_SERVICE_ERROR,

    // Creator Verification
    IDENTITY_VERIFICATION_REQUIRED,
    ACCOUNT_HOLDER_MISMATCH,
    INVALID_BANK_ACCOUNT,
    UNSUPPORTED_BANK,
    CREATOR_ALREADY_VERIFIED,
    CREATOR_VERIFICATION_NOT_FOUND,
    RENEWAL_TOO_EARLY,
    ACCOUNT_CHANGE_LOCKED,
    ACCOUNT_UNCHANGED,
    BANK_ACCOUNT_VERIFICATION_FAILED,
    PORTONE_PARTNER_CREATE_FAILED,
    PORTONE_PARTNER_UPDATE_FAILED,
    PORTONE_API_ERROR,

    // Settlement & Payment
    PARTNER_REGISTRATION_FAILED,
    PAYMENT_ERROR,

    // Generic
    MEMBER_NOT_FOUND,
}