name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Run tests
      run: ./gradlew test --continue --info
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-results
        path: build/test-results/test/
    
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-reports
        path: build/reports/tests/test/
    
    - name: Publish test results
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: Gradle Tests
        path: build/test-results/test/TEST-*.xml
        reporter: java-junit
    
    - name: Build application
      run: ./gradlew build -x test
    
    - name: Build Docker image
      run: |
        docker build -t tropig-backend:${{ github.sha }} .
        docker tag tropig-backend:${{ github.sha }} tropig-backend:latest
    
    - name: Push to GitHub Container Registry
      if: github.event_name == 'push'
      run: |
        echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker tag tropig-backend:${{ github.sha }} ghcr.io/${{ github.repository }}/tropig-backend:${{ github.sha }}
        docker tag tropig-backend:${{ github.sha }} ghcr.io/${{ github.repository }}/tropig-backend:latest
        docker push ghcr.io/${{ github.repository }}/tropig-backend:${{ github.sha }}
        docker push ghcr.io/${{ github.repository }}/tropig-backend:latest
